### ISSUE TITLE
Missing comma on lines 88 and 89, fails wifi connect

### ISSUE THREAD

**Issue by Lou-Menz** [G6EJD/ESP-Sensor-Server-Client#2]
88 wifiMulti.addAP("ssid_from_AP_1"  "your_password_for_AP_1");
  change to:
  wifiMulti.addAP("ssid_from_AP_1" ,  "your_password_for_AP_1");

 89  wifiMulti.addAP("ssid_from_AP_2"  "your_password_for_AP_2");
change to:
wifiMulti.addAP("ssid_from_AP_2" ,  "your_password_for_AP_2");

**Comment by G6EJD** [comment]
Corrected the code, thank you.

**Comment by Lou-Menz** [comment]
Thank YOU! Glad to help.
